### ISSUE TITLE
Drop-off from the highest bitscore parameter '-r' only accepts integers

### ISSUE THREAD

**Issue by xapple** [lanzen/CREST#11]
When trying to adjust CREST for long reads, I attempted to lower the "drop-off from the highest bitscore" to half a percent. 

Adding the "-r 0.5" parameter produces the following exception:

    Usage: classify [options]
    
    classify: error: option -r: invalid integer value: '0.5'

There might be a parsing problem for the command line arguments?

**Comment by lanzen** [comment]
Thank you for finding this out! I had never tried with decimal dropoff cutoffs. This is now fixed and included in the source code or the new release v3.2.2.
