### ISSUE TITLE
Installation error with zc.buildout

### ISSUE THREAD

**Issue by alex-bagnoud** [lanzen/CREST#7]
Dear lanzen,

I just tried to install ```LCAClassifierV3.0.7.tar.gz``` but I got this error when running ```install.sh```:

```
Alex@eduroam-028-060:~/Downloads/LCAClassifier$ ./install.sh 
ez_setup.py is deprecated and when using it setuptools will be pinned to 33.1.1 since it's the last version that supports setuptools self upgrade/installation, check https://github.com/pypa/setuptools/issues/581 for more info; use pip to install setuptools
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-33.1.1.zip
Extracting in /var/folders/56/65_b_crs0cxdp5wz605zn4hw0000gn/T/tmpjllc1i
Now working in /var/folders/56/65_b_crs0cxdp5wz605zn4hw0000gn/T/tmpjllc1i/setuptools-33.1.1
Building a Setuptools egg in /var/folders/56/65_b_crs0cxdp5wz605zn4hw0000gn/T/bootstrap-uuFMRn
warning: no files found matching '*' under directory 'setuptools/_vendor'
/var/folders/56/65_b_crs0cxdp5wz605zn4hw0000gn/T/bootstrap-uuFMRn/setuptools-33.1.1-py2.7.egg
no previously-included directories found matching 'doc'
no previously-included directories found matching 'old-tutorial'
Creating directory '/Users/Alex/.Trash/LCAClassifier 11.31.13/develop-eggs'.
Generated script '/Users/Alex/.Trash/LCAClassifier 11.31.13/bin/buildout'.
Upgraded:
  zc.buildout version 2.9.5,
  setuptools version 39.2.0;
restarting.
Generated script '/Users/Alex/.Trash/LCAClassifier 11.31.13/bin/buildout'.
Develop: '/Users/Alex/.Trash/LCAClassifier 11.31.13/.'
Getting distribution for 'zope.testrunner'.
Using unpack_wheel() shim over the deprecated wheel_to_egg() hook.
Please update your wheel extension implementation for one that installs a .whl
handler in zc.buildout.easy_install.UNPACKERS
While:
  Installing.
  Getting section test.
  Initializing section test.
  Installing recipe zc.recipe.testrunner.
  Getting distribution for 'zope.testrunner'.
Error: Wheels are not supported
```
I think it has to do with version 2.9.5 of zc.buildout, as explained [here](https://github.com/buildout/buildout/pull/428) . So this issue might be fixed by using a later version of zc.buildout, which I tried to do by modifying the ```buildout.cfg``` file by specifying a new version with ```zc.buildout=2.10.0```, but this did not help.

Any idea how to solve this? Thanks in advance for your help!

**Comment by lanzen** [comment]
Dear Alex,

Thank you for your very detailed report and for trying to solve this yourself. It is something I have struggled with before and the current solution has worked until now for me, but it seems nearly impossible to maintain compability with zc.buildout. I want to replace the whole use of setuptools and replace it but I have not had time to fix this. 

You could try to install python-wheel and see if this helps.

Best,
Anders

**Comment by alex-bagnoud** [comment]
Hey Anders,
Thanks for your quick reply! I overcame this issue by using [MEGAN5](http://ab.inf.uni-tuebingen.de/software/megan5/) instead of CREST, as described on your [webpage](http://services.cbu.uib.no/supplementary/crest/CREST_Tutorial.html). Apparently, the Silvamod128 tree is not compatible with the latest version MEGAN6.
Best regards,
Alex
