### ISSUE TITLE
Error: Couldn't find a distribution for 'zc.recipe.testrunner'.

### ISSUE THREAD

**Issue by potant** [lanzen/CREST#8]
Trying by either of the following ways the above error arises...
1) tar -xvzf LCAClassifier3.0.7.tar.gz
     cd LCAClassifier 
       ./install.sh

2) wget https://pypi.python.org/packages/source/z/zc.buildout/zc.buildout-2.2.1.tar.gz
  tar xvzf zc.buildout-2.2.1.tar.gz
  cd zc.buildout-2.2.1
  sudo python setup.py install  
  wget http://services.cbu.uib.no/supplementary/crest/LCAClassifier2.0.2.tar.gz
  cd LCAClassifier
  buildout

I am using debian stretch
Any idea?

**Comment by potant** [comment]
the error in more detail
Develop: '/mnt/big/tools/CREST/LCAClassifier/.'
Couldn't find index page for 'zc.recipe.testrunner' (maybe misspelled?)
Getting distribution for 'zc.recipe.testrunner'.
Couldn't find index page for 'zc.recipe.testrunner' (maybe misspelled?)
While:
  Installing.
  Getting section test.
  Initializing section test.
  Installing recipe zc.recipe.testrunner.
  Getting distribution for 'zc.recipe.testrunner'.
Error: Couldn't find a distribution for 'zc.recipe.testrunner'.

**Comment by lanzen** [comment]
Hi,

Thank you for your detailed error report. However, I am not sure I can help you and I cannot reproduce this error. Can you try to also download the development version using git clone?

Anders

**Comment by lanzen** [comment]
Thanks to an update in zc.buildout the newest version now seems to install without problems in most Linux distros and I have removed the specific version requirements. Can you try if it has resolved your issue as well?
