### ISSUE TITLE
silvamod128.tar.gz not found

### ISSUE THREAD

**Issue by potant** [lanzen/CREST#9]
It seems that the file silvamod128.tar.gz is not there it is supposed to be, so the following comes up:

Installing silvamod.
Error: Error downloading extends for URL http://services.cbu.uib.no/supplementary/crest/silvamod128.tar.gz: HTTP Error 404: Not Found

Any idea?

**Comment by lanzen** [comment]
Hi,

Sorry for not responding to this for so long. The server where the files
were hosted apparently is broken and we have to search for a new home for
the CREST database. I am currently setting up a temporary solution and I
will let you know when it works again. Sorry for the delay.

Best regards,
Anders

**Comment by lanzen** [comment]
Hi,

I admit that this has taken much too long, but a new website is now up and this error should no longer occur. The URL is the forwarded from the one of before so you don't have to do anything except running the installation script again

Anders

**Comment by xapple** [comment]
Apparently the redirect at `/~andersl/crest/supplementary_web/silvamod128.tar.gz` is now also 404.

**Comment by lanzen** [comment]
Apparently the redirect to /crest is no longer working. I have contacted the helpdesk of the Informatics Dept. at the Univ. of Bergen where the file server is hosted and it should be fixed shortly. I will keep you updated.

**Comment by lanzen** [comment]
The redirect should now be fixed again. Please try to re-run buildout.py
